name: Books API CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install fastapi
          pip install pydantic
          pip install pytest-asyncio
          
      - name: Run tests
        run: |
          pytest
          
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to project directory
            cd /path/to/books-api
            
            # Pull latest changes
            git pull origin main
            
            # Install/update dependencies
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
            # Restart the API service
            # Note: You'll need to set up a service manager (like systemd) first
            sudo systemctl restart books-api || echo "Service restart failed"